service: govuk-asset-size-checker

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7

functions:
  checker:
    handler: handler.checker
    environment: ${file(env.json):local} # load env vars from `env.json`
    # Note: this works, but does not output anything!
    # events:
    #   - schedule: rate(1 minute)

useDotenv: true

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: True
    lambda:
      # mountCode: True
    docker:
      sudo: False
  stages:
    local:
